version: '3.8'

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

  expenses:
    image: redis:alpine3.19
    environment:
      DB_URL: postgresdb
      DB_USER: postgres
      DB_PASS: pass1234
      DB_NAME: expenses
    ports:
      - "1234:1234"
    depends_on:
      - postgresdb
volumes:
  postgres:

